name: atividade_consumo_api
description: Aplicacao de linha de comando para consulta de Pokemon na PokeAPI.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.5.0
